### ISSUE TITLE
PLEASE REWRITE FOR PHASER 3.20.1!!!

### ISSUE THREAD

**Issue by Thundros** [Colbydude/phaser-3-palette-swapping-example#1]
@Colbydude Hello, I came across your AMAZING demo & I would really like to integrate it into my project, but 2 small problems. 1 ) It uses an older version of phaser 3. & 2 ) I use texture atlases for player. Not Sprite sheets.

Could you please be so kind as to rewrite this for 3.20.1?

Thank you SO much & have a GREAT day!

**Comment by Colbydude** [comment]
Hi @Thundros, thanks for reaching out.

Example has been updated for 3.20.1. Simple bug involving temp texture deletion.

As far as texture atlases go, I'm sure the same is achievable, but this example is specific to sprite sheets, so I will not be updating it to do so. However, if you'd like to open a PR with an example of performing palette swapping with texture atlases, have at it.

Thank you!
