### ISSUE TITLE
Add Texture Atlas?

### ISSUE THREAD

**Issue by Thundros** [Colbydude/phaser-3-palette-swapping-example#2]
Hi @Colbydude ! I recently tried out your sprite sheet version of the 3.20.1 update & I must say, This project is AMAZING! PLEASE keep up the WONDERFUL work!

I really don't want to have to re-color all my Texture Atlas sprites & I would really like to use Palette switcher on my Character Texture Atlases.

I would be MORE than happy to beta test it for you!

Thank you SO much & keep up the GREAT work! =)

**Comment by Colbydude** [comment]
Hi Thundros,

As I said in the previous issue, this example is specific to sprite sheets and I will be not be updating to support texture atlases unless _someone else_ wants to open a PR to add the feature. A good amount of the logic should still be applicable.

Cheers.
